# Generated by Django 5.1.5 on 2025-02-02 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название приза')),
                ('description', models.TextField(blank=True, verbose_name='Описание приза')),
                ('probability', models.FloatField(default=0.0, verbose_name='Вероятность выпадения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='prizes/', verbose_name='Изображение приза')),
                ('checked', models.BooleanField(default=False, verbose_name='Редкий')),
                ('prize_type', models.CharField(choices=[('money', 'Деньги'), ('freespin', 'Фриспины'), ('product', 'Товар')], default='product', max_length=20, verbose_name='Тип приза')),
                ('money_amount', models.IntegerField(default=0, verbose_name='Сумма денег')),
                ('freespin_amount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во фриспинов')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='Пользователь')),
                ('invited_users', models.PositiveIntegerField(default=0, verbose_name='Количество приглашенных пользователей')),
                ('available_spins', models.PositiveIntegerField(default=0, verbose_name='Доступные вращения')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('referal_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время вращения')),
                ('prize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wheel_of_fortune.prize', verbose_name='Выпавший приз')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheel_of_fortune.users', verbose_name='Пользователь')),
            ],
        ),
    ]
